create database Grocery;
use Grocery;
-- 1. Supplier Table
CREATE TABLE IF NOT EXISTS supplier (
    sup_id TINYINT PRIMARY KEY,
    sup_name VARCHAR(255),
    address TEXT
);

-- 2. Categories Table
CREATE TABLE IF NOT EXISTS categories (
    cat_id TINYINT PRIMARY KEY,
    cat_name VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS employees (
    emp_id TINYINT PRIMARY KEY,
    emp_name VARCHAR(255),
    hire_date VARCHAR(255)
);

-- 4. Customers Table
CREATE TABLE IF NOT EXISTS customers (
    cust_id SMALLINT PRIMARY KEY,
    cust_name VARCHAR(255),
    address TEXT
);

-- 5. Products Table
CREATE TABLE IF NOT EXISTS products (
    prod_id TINYINT PRIMARY KEY,
    prod_name VARCHAR(255),
    sup_id TINYINT,
    cat_id TINYINT,
    price DECIMAL(10,2),
    FOREIGN KEY (sup_id) REFERENCES supplier(sup_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (cat_id) REFERENCES categories(cat_id)
        ON UPDATE CASCADE ON DELETE CASCADE
);

-- 6. Orders Table
CREATE TABLE IF NOT EXISTS orders (
    ord_id SMALLINT PRIMARY KEY,
    cust_id SMALLINT,
    emp_id TINYINT,
    order_date VARCHAR(255),
    FOREIGN KEY (cust_id) REFERENCES customers(cust_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (emp_id) REFERENCES employees(emp_id)
        ON UPDATE CASCADE ON DELETE CASCADE
);

-- 7. Order_Details Table
CREATE TABLE IF NOT EXISTS order_details (
    ord_detID SMALLINT AUTO_INCREMENT PRIMARY KEY,
    ord_id SMALLINT,
    prod_id TINYINT,
    quantity TINYINT,
    each_price DECIMAL(10,2),
    total_price DECIMAL(10,2),
    FOREIGN KEY (ord_id) REFERENCES orders(ord_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (prod_id) REFERENCES products(prod_id)
        ON UPDATE CASCADE ON DELETE CASCADE
);

select * from categories;
select * from customers;
select * from employees;
select * from order_details;
select * from orders;
select * from products;
select * from supplier;

-- 1️. Customer Insights
-- Gain an understanding of customer engagement and purchasing behavior.


-- 1. How many unique customers have placed orders?

select count(distinct cust_id) as Uniquecust from orders;

-- 2. Which customers have placed the highest number of orders?

select c.cust_id,c.cust_name, count(o.ord_id) as number_of_orders
from orders o
join customers c on o.cust_id = c.cust_id
group by cust_id,cust_name
order by number_of_orders desc;


/* -- Most odered details
select c.cust_name,
count(o.cust_id) as number_of_orders from customers c
join orders o on c.cust_id = o.cust_id
join order_details od on o.ord_id = od.ord_id
group by  c.cust_name
order by number_of_orders desc; */

-- 3. What is the total and average purchase value per customer?

select c.cust_id,c.cust_name,sum(od.quantity * od.each_price) as Total_sum,avg(od.quantity * od.each_price) as average_purchase_value
from customers c join orders o on c.cust_id = o.cust_id join order_details od on o.ord_id = od.ord_id
group by c.cust_id order by c.cust_id;

-- 4. Who are the top 5 customers by total purchase amount? 

select c.cust_id, c.cust_name,sum(od.quantity*od.each_price)
as total_amount_purchase from customers c
join orders o on c.cust_id= o.cust_id
join order_details od on o.ord_id=od.ord_id
group by c.cust_id, c.cust_name
order by total_amount_purchase 
desc limit 5;

SELECT o.cust_id, SUM(od.total_price) AS total_purchase
FROM orders o
JOIN order_details od ON o.ord_id = od.ord_id
GROUP BY o.cust_id
ORDER BY total_purchase DESC
LIMIT 5;

/*c.cust_id,
SUM(od.total_price * od.each_price) as total_purchase_value
from customers c
join orders o on o.ord_id = od.ord_id
join order_details od on o.ord_id = od.ord_id
group by o.cust_id
order by total_purchase_value desc
limit 5;*/


/* 2. Product Performance */

-- 2.1 How many products exist in each category?

select c.cat_id,c.cat_name,count(p.prod_name)
as Number_of_Products from categories c
join products p on c.cat_id = p.cat_id
group by c.cat_name,c.cat_id;


-- 2.2 What is the average price of products by category?
select c.cat_name,avg(p.price) as average_price from products p
join categories c on c.cat_id = p.cat_id
group by c.cat_name; 


/* SELECT c.cat_name,
AVG(p.price) AS average_price
FROM categories c
JOIN products p ON c.cat_id = p.cat_id
GROUP BY c.cat_name
ORDER BY average_price DESC; */

select p.prod_id,c.cat_name,p.prod_name,avg(p.price) as average_price from products p
join categories c on p.cat_id = c.cat_id
group by c.cat_name,p.prod_name,p.prod_id; 

-- 3. Which products have the highest total sales volume (by quantity)?
select p.prod_name,
sum(od.quantity) as total_sales_volume
from products p
join order_details od on p.prod_id = od.prod_id
group by  p.prod_name
order by total_sales_volume desc;


-- 4. What is the total revenue generated by each product?

select p.prod_name, sum(od.total_price) as revenue_generated from products p
join order_details od on p.prod_id = od.prod_id
group by p.prod_name
order by revenue_generated desc limit 5;

-- 5. How do product sales vary by category and supplier?

select c.cat_name,s.sup_name,
sum(od.quantity * od.each_price) as total_sales
from order_details od
join products p on od.prod_id = p.prod_id
join categories c on p.cat_id = c.cat_id
join supplier s on p.sup_id = s.sup_id
group by c.cat_name, s.sup_name
order by c.cat_name, total_sales desc;

SELECT c.cat_name, s.sup_name, SUM(od.total_price) AS total_sales_revenue
FROM categories c
JOIN products p ON c.cat_id = p.cat_id
JOIN supplier s ON p.sup_id = s.sup_id
JOIN order_details od ON p.prod_id = od.prod_id
GROUP BY c.cat_name, s.sup_name
ORDER BY total_sales_revenue DESC;


-- 3. Sales and Order Trends
-- Analyze business performance through orders and revenue over time.

-- 1. How many orders have been placed in total?
select count(*) as total_orders from orders; 

-- 2. What is the average value per order?
select avg(total_price) as average_order_value from order_details;

SELECT AVG(order_total) AS avg_order_value
FROM (
    SELECT o.ord_id, SUM(od.total_price) AS order_total
    FROM orders o
    JOIN order_details od ON o.ord_id = od.ord_id
    GROUP BY o.ord_id
) AS order_summary;

-- 3. On which dates were the most orders placed?
SELECT order_date, COUNT(ord_id) AS number_of_orders
FROM orders
GROUP BY order_date
ORDER BY number_of_orders DESC;
-- LIMIT 1;

-- 4. What are the monthly trends in order volume and revenue?
select
 month(str_to_date(order_date,"%m/%d/%Y")) as month,
count(distinct o.ord_id) as volume,
sum(od.quantity*od.each_price) as revenue
from orders o
join order_details od on o.ord_id= od.ord_id
group by month;


-- 5. How do order patterns vary across weekdays and weekends?
with cte1 as 
(select ord_id,dayofweek(str_to_date(order_date,"%m/%d/%Y")) as days from orders),
cte2 as 
(select *,case when days IN (1, 7) THEN 'Weekend'else 'Weekday'end as order_type from cte1)
select distinct order_type,count(ord_id) over (partition by order_type) as no_of_order from cte2;


-- 4. Supplier Contribution 
-- Identify the most active and profitable suppliers.
-- ● 4.1 How many suppliers are there in the database? 

select count(sup_id) as supplier_id from supplier;

-- ● 4.2 Which supplier provides the most products? 

select s.sup_name, count(p.prod_id) as number_of_products from supplier s
join products p on s.sup_id = p.sup_id
group by s.sup_name
order by number_of_products desc;

-- ● 4.3 What is the average price of products from each supplier? 

select s.sup_name, avg(p.price) as Avg_price from supplier s
join products p on s.sup_id = p.sup_id
group by s.sup_name;

-- ● 4.4 Which suppliers contribute the most to total product sales (by revenue)? 
select s.sup_name, sum(od.total_price) as total_revenue from supplier s
join products p on s.sup_id = p.sup_id
join order_details od on p.prod_id = od.prod_id
group by s.sup_name
order by total_revenue desc;


-- 5. Employee Performance 
-- Assess how employees are handling and influencing sales. 
-- ● 5.1 How many employees have processed orders? 
select count(distinct emp_id) as Total_Employees from employees;

-- ● 5.2  Which employees have handled the most orders? 

select e.emp_name,count(o.ord_id) as handled_orders from employees e
join orders o on  e.emp_id = o.emp_id
group by e.emp_name
order by handled_orders desc; 

-- ● 5.3 What is the total sales value processed by each employee? 

select e.emp_name, sum(od.total_price) as total_sales_value from employees e
join orders o on e.emp_id = o.emp_id
join order_details od on o.ord_id = od.ord_id
group by e.emp_name
order by total_sales_value desc;

-- ● 5.4 What is the average order value handled per employee? 

select e.emp_name, avg(od.total_price) as average_order_value
from employees e
join orders o on e.emp_id = o.emp_id
join order_details od on o.ord_id = od.ord_id
group by e.emp_name;

-- 6. Order Details Deep Dive 
-- Explore item-level sales patterns and pricing behavior. 
-- ● 6.1 What is the relationship between quantity ordered and total price? 
SELECT
    COUNT(*) AS total_records,
    SUM(CASE WHEN total_price = (quantity * each_price) THEN 1 ELSE 0 END) AS matching_records
FROM order_details;


SELECT quantity,
AVG(total_price) AS average_total_price
FROM order_details
GROUP BY quantity
ORDER BY quantity;


 select od.ord_id, od.prod_id, od.quantity, od.each_price,
(od.quantity * od.each_price) as total_price_for_item
from order_details od;
-- ● 6.2 What is the average quantity ordered per product? 

SELECT p.prod_name, AVG(od.quantity) AS average_quantity_ordered
FROM products p
JOIN order_details od ON p.prod_id = od.prod_id
GROUP BY p.prod_name
ORDER BY average_quantity_ordered DESC;


-- ● 6.3 How does the unit price vary across products and orders?
SELECT p.prod_name, od.each_price AS product_catalog_price,
    od.ord_id,
    od.each_price AS ordered_unit_price
FROM products p
JOIN order_details od ON p.prod_id = od.prod_id
ORDER BY p.prod_name, od.order_id;

-- 1.1
SELECT COUNT(DISTINCT cust_id) AS unique_customers
FROM orders;
-- 1.2 
SELECT cust_id, COUNT(*) AS total_orders
FROM orders
GROUP BY cust_id
ORDER BY total_orders DESC;

-- 1.5 
SELECT o.cust_id, SUM(od.total_price) AS total_purchase
FROM orders o
JOIN order_details od ON o.ord_id = od.ord_id
GROUP BY o.cust_id
ORDER BY total_purchase DESC
LIMIT 5;

-- 2.4

SELECT p.prod_id, p.prod_name, SUM(od.total_price) AS revenue
FROM products p
JOIN order_details od ON p.prod_id = od.prod_id
GROUP BY p.prod_id, p.prod_name
ORDER BY revenue DESC;

-- 2.1
SELECT cat_id, COUNT(*) AS product_count
FROM products
GROUP BY cat_id;
-- 3.4
SELECT SUBSTRING(order_date, 1, 7) AS month, 
       COUNT(*) AS total_orders, 
       SUM(od.total_price) AS total_revenue
FROM orders o
JOIN order_details od ON o.ord_id = od.ord_id
GROUP BY SUBSTRING(order_date, 1, 7)
ORDER BY month;
-- 3.3
SELECT order_date, COUNT(*) AS total_orders
FROM orders
GROUP BY order_date
ORDER BY total_orders DESC;
-- 4.5
-- 5.2
SELECT emp_id, COUNT(*) AS total_orders
FROM orders
GROUP BY emp_id
ORDER BY total_orders DESC;



